# Generated by Django 3.1.6 on 2021-02-09 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(
                default='0', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='buys.order'),
            preserve_default=False,
        ),
    ]
