# Generated by Django 3.1.6 on 2021-02-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0005_remove_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
    ]
