# Generated by Django 3.1.6 on 2021-02-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0006_remove_orderitem_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
