# Generated by Django 3.1.6 on 2021-02-09 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0008_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='buys.buy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='buys.item'),
        ),
    ]
