# Generated by Django 3.1.6 on 2021-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210204_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(default='no pw', max_length=20),
            preserve_default=False,
        ),
    ]
