# Generated by Django 3.1.6 on 2021-02-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_host_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
