# Generated by Django 3.1.6 on 2021-02-05 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hostuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostUser',
        ),
    ]
